### ISSUE TITLE
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11

### ISSUE THREAD

**Issue by mksakeesh** [fake-useragent/fake-useragent#100]
Ran below code and got error as mentioned below

version used :- fake-useragent==0.1.11

`
import requests
from fake_useragent import UserAgent
from bs4 import BeautifulSoup
ua = UserAgent()
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\site-packages\fake_useragent\utils.py", line 67, in get
    context=context,
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\site-packages\fake_useragent\utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\site-packages\fake_useragent\utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "C:\Users\meuser\Anaconda3\envs\env001\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
`

**Comment by oren-nonamesecurity** [comment]
Yes, this is super annoying and spamming. Can this be fixed?

**Comment by melroy89** [comment]
Should be fixed by now.
