### ISSUE TITLE
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11: Timed out

### ISSUE THREAD

**Issue by matej2** [fake-useragent/fake-useragent#103]
Hello,

When I call ua.random, I get timeout error. I have searched and found similar issue. I updated my code accordingly. My code:

```Python
ua = UserAgent(verify_ssl=False, cache=False)

 firefox_profile.set_preference("general.useragent.override", ua.random)
```

- Python:  3.6.8
- Fake-useragent: 0.1.11

Error stack trace:

```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/YR0vVpCM/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/apartment-scraper-YR0vVpCM/lib/python3.6/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/home/user/.local/share/virtualenvs/apartment-scraper-YR0vVpCM/lib/python3.6/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/home/user/.local/share/virtualenvs/apartment-scraper-YR0vVpCM/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by mattprice0009** [comment]
We also have this same issue, suddenly - as of about 7 days ago.

**Comment by Destroyerillya** [comment]
UP we also have this same issue, pls fix this.

**Comment by Nephthalim** [comment]
I also have the same issue.

**Comment by akbar-amin** [comment]
The website has been down for some time now. However, [this repository](https://github.com/tamimibrahim17/List-of-user-agents) seems to have a ton of them saved.

**Comment by ariel-frischer** [comment]
> The website has been down for some time now. However, [this repository](https://github.com/tamimibrahim17/List-of-user-agents) seems to have a ton of them saved.

How to use that repository with this package??

**Comment by gagassurya19** [comment]
did you found a solution how to use that repository?

**Comment by Destroyerillya** [comment]
@gagassurya19 use lib user_agent on pypi located.

**Comment by amriteshonly4u** [comment]
Again facing same issue please fix its deployed in live project
