### ISSUE TITLE
Page http://www.w3schools.com/browsers/browsers_stats.asp has changed.

### ISSUE THREAD

**Issue by alextheinsomniac** [fake-useragent/fake-useragent#12]
Below is the traceback.

The page http://www.w3schools.com/browsers/browsers_stats.asp doesn't have a table with class="reference no translate".

I guess the layout has changed in the last 24 hours.

from fake_useragent import UserAgent
ua = UserAgent(cache=False)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/fake.py", line 12, in **init**
    self.data = load()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 82, in load
    for item in get_browsers():
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 29, in get_browsers
    html = html.split('<table class="reference notranslate">')[1]
IndexError: list index out of range

http://www.w3schools.com/browsers/browsers_stats.asp

**Comment by dreyco676** [comment]
Maybe we should switch to use http://www.useragentstring.com/pages/useragentstring.php

**Comment by dreyco676** [comment]
Actually we should totally do this there is an API. http://www.useragentstring.com/pages/api.php

**Comment by alextheinsomniac** [comment]
APIs should be more stable than web pages but the part that is broken gives the percentage of users using each version of different browsers.
The API you suggest seems to only convert from UA strings to details about the browser. Correct me if I'm wrong.

**Comment by dreyco676** [comment]
No that's true, no percentages that I can see. I'm getting a similar error. Looks like i need to open a new issue.

Traceback (most recent call last):
  File "C:/Users/G540924/IdeaProjects/pytrends/examples/example.py", line 10, in <module>
    fake_ua = UserAgent()
  File "C:\Anaconda3\lib\site-packages\fake_useragent\fake.py", line 10, in **init**
    self.data = load_cached()
  File "C:\Anaconda3\lib\site-packages\fake_useragent\utils.py", line 140, in load_cached
    update()
  File "C:\Anaconda3\lib\site-packages\fake_useragent\utils.py", line 135, in update
    write(load())
  File "C:\Anaconda3\lib\site-packages\fake_useragent\utils.py", line 82, in load
    for item in get_browsers():
  File "C:\Anaconda3\lib\site-packages\fake_useragent\utils.py", line 29, in get_browsers
    html = html.split('<table class="reference notranslate">')[1]
IndexError: list index out of range

**Comment by alextheinsomniac** [comment]
There are already two pull requests for the fix.
Change line 29 of fake_useragent\utils.py
-    html = html.split('<table class="reference notranslate">')[1]
-    html = html.split('<table class="w3-table-all notranslate">')[1]

It works. Make the change in your source for now. I'm sure the pull requests will be dealt with soon.

**Comment by dreyco676** [comment]
I'll give it a try. I know we are using it in our module Pytrends as a requirement, so I'll put a patch in place.

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/pull/13 fixes and was merged, new version is on pypi

I like proposal about JSON API, but http://www.w3schools.com/browsers/browsers_stats.asp is used for browser usage stats to get more accurate `ua.random` feature

I am open for another proposals

**Comment by hellysmile** [comment]
useragentstring api is not for grabbing data as I see
