### ISSUE TITLE
ua.update() InderError

### ISSUE THREAD

**Issue by BoogalooLi** [fake-useragent/fake-useragent#130]
While using ua.update(), then I get errors below

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/Users/li/opt/anaconda3/envs/stock/lib/python3.7/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/Users/li/opt/anaconda3/envs/stock/lib/python3.7/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

**Comment by NikitaMishin** [comment]
same issue

**Comment by Tsangares** [comment]
Same

**Comment by Tsangares** [comment]
Actually it went away after a few minutes.... Not sure. 

This was the error:
```

WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/path/to/directory/env/lib/python3.10/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/path/to/directory/env/lib/python3.10/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
```

Must have been booting up the Heroku instance.

**Comment by Tsangares** [comment]
Easy fix might be to just retry once with a delay if this fails.

**Comment by Tsangares** [comment]
Duplicate of #129 and #113

**Comment by vsoch** [comment]
+1 - am hitting this just using it. It doesn't fail but looks pretty ugly, would be nice to get a fix!

```bash
WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/opt/conda/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
```

**Comment by melroy89** [comment]
Should be solved by now. Please update to the latest release: `pip install --upgrade fake-useragent`
