### ISSUE TITLE
MacOs / SSL: CERTIFICATE_VERIFY_FAILED error when running executeable program?

### ISSUE THREAD

**Issue by Rapid1898-code** [fake-useragent/fake-useragent#131]
Hello - i have the following issue when using fake-useragent in an executeable program on MacOS -
When i run the py-program on my MacOS everything works fine - then create an executeable program using pyinstaller and also the created program ran fine on my MacOS

But when i try to run this on another MacOS i get the below error message when starting the program.
I have this issues now on at least 2 other MacOS - in the past everything worked fine.

Any ideas what could be the problem here?

```
Last login: Thu Aug 11 19:05:59 on ttys000
/Users/guillaumelacourt/Downloads/max_trial/collTimeform ; exit;                
guillaumelacourt@Guillaumes-MacBook-Pro ~ % /Users/guillaumelacourt/Downloads/max_trial/collTimeform ; exit;
Checking Browser driver...
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "urllib/request.py", line 1342, in do_open
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "http/client.py", line 1424, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_useragent/utils.py", line 64, in get
  File "urllib/request.py", line 214, in urlopen
  File "urllib/request.py", line 517, in open
  File "urllib/request.py", line 534, in _open
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 1385, in https_open
  File "urllib/request.py", line 1345, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_useragent/utils.py", line 154, in load
  File "fake_useragent/utils.py", line 97, in get_browsers
  File "fake_useragent/utils.py", line 84, in get
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
Traceback (most recent call last):
  File "urllib/request.py", line 1342, in do_open
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "http/client.py", line 1424, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_useragent/utils.py", line 64, in get
  File "urllib/request.py", line 214, in urlopen
  File "urllib/request.py", line 517, in open
  File "urllib/request.py", line 534, in _open
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 1385, in https_open
  File "urllib/request.py", line 1345, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_useragent/utils.py", line 154, in load
  File "fake_useragent/utils.py", line 97, in get_browsers
  File "fake_useragent/utils.py", line 84, in get
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib/request.py", line 1342, in do_open
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "http/client.py", line 1424, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
socket.timeout: _ssl.c:1105: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_useragent/utils.py", line 64, in get
  File "urllib/request.py", line 214, in urlopen
  File "urllib/request.py", line 517, in open
  File "urllib/request.py", line 534, in _open
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 1385, in https_open
  File "urllib/request.py", line 1345, in do_open
urllib.error.URLError: <urlopen error _ssl.c:1105: The handshake operation timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "collTimeform.py", line 61, in <module>
  File "fake_useragent/fake.py", line 69, in __init__
  File "fake_useragent/fake.py", line 75, in load
  File "fake_useragent/utils.py", line 250, in load_cached
  File "fake_useragent/utils.py", line 245, in update
  File "fake_useragent/utils.py", line 187, in load
  File "fake_useragent/utils.py", line 84, in get
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
[3141] Failed to execute script 'collTimeform' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by NVD94** [comment]
The script in [this](https://github.com/Unbabel/COMET/issues/29#issuecomment-945601519) comment solved the problem for me .

**Comment by melroy89** [comment]
It's solved now.

`pip install --upgrade fake-useragent`
