### ISSUE TITLE
HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by Rapid1898-code** [fake-useragent/fake-useragent#157]
Hello - i was using fake-useragent for a long time - and today suddenly i get this error message when running the program -

Till now i used this version:
fake-useragent            0.1.11
with this pull-request for using only user-agents from newest browsers:
https://github.com/fake-useragent/fake-useragent/pull/122

With that i get the error at the bottom..

I can upgrade to fake-useragent            1.1.0
But with that the keyword num_newest_uas can not be used anymore.

Is there any way to get only the newest useragents with 1.1.0 also?
And is there any way to prevent the existing program with version 0.1.11 from suddenly crashing?
I have created many executeable files using pyinstaller - and they seems to work suddenly not anymore...?

I used this call in the past:
```
  ua = UserAgent(verify_ssl=False, num_newest_uas=2)
  userAgent = ua.random
```

Why is this error suddenly appearing?

```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 164, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 143, in get_browser_versions
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome
Traceback (most recent call last):
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 164, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 143, in get_browser_versions
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "C:\Users\WRSPOL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen      
    return opener.open(url, data, timeout)
  File "C:\Users\WRSPOL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\WRSPOL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\WRSPOL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\WRSPOL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\WRSPOL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\Fiverr\ORDER\robalf\getLang.py", line 44, in <module>
    ua = UserAgent(verify_ssl=False, num_newest_uas=2)
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\fake.py", line 78, in __init__
    self.load()
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\fake.py", line 84, in load
    self.data = load_cached(
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 187, in load
    ret = json.loads(get(
  File "C:\DEV\.venv\test\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by ogsamrat** [comment]
Check my issue for a better explanation of this https://github.com/fake-useragent/fake-useragent/issues/158

**Comment by HackerSM9** [comment]
Same Problem I am getting

**Comment by melroy89** [comment]
So we actually want to migrate to a new data source with more up to date user-agent strings, since the current ones can be quite outdated. Would that solve your missing `num_newest_uas` option?

**Comment by Rapid1898-code** [comment]
Hello - i don´t think this will solve the problem with the "num_newest_uas".
I used this parameter in the case when a website noted me that i have to use an actual useragent when scraping the data.
When i understand it correct, with this parameter it was possible to get only the x newest useragents when i use eg. ua.random(). This is what i would need also in the new version.

But so long this parameter didn´t ever get it in the final version i think.

**Comment by melroy89** [comment]
No indeed. But I said we are working on migration the data source to a better one. Giving you always a real user agent string. So that would make this parameter obsolete, since fake user agent will then always return an up to date string.

**Comment by Rapid1898-code** [comment]
Hello - that would be great when there are only returning actual fake user agents.

**Comment by josuemtzmo** [comment]
I had this issue and updating to version `1.1.1` fixed it.
