### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mingot** [fake-useragent/fake-useragent#20]
Seems that some parameters have changed and it is causing a bug:

```
>>> import fake_useragent
>>> fake_useragent.UserAgent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/usr/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/usr/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/usr/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 92, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/usr/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 55, in get_browser_versions
    html = html.split('<div id=\'liste\'>')[1]
IndexError: list index out of range
```

**Comment by hellysmile** [comment]
Can You try latest 0.1.0 version? It was fixed! And new version has been released to PyPi today.

**Comment by nourspace** [comment]
I can't find any `<div id='liste'>` anymore on the stats page
http://www.w3schools.com/browsers/browsers_stats.asp

**Comment by hellysmile** [comment]
https://travis-ci.org/hellysmile/fake-useragent/builds/147978486 Have Tou tried latest PyPi version?

**Comment by nourspace** [comment]
It works now :tada: ! Thanks

for some reason pip was always installing the older cached version.
Good job with adding the version to the json file. :+1:

**Comment by hellysmile** [comment]
Seems fixed
