### ISSUE TITLE
index out of range error on initialization

### ISSUE THREAD

**Issue by handfulofteeth** [fake-useragent/fake-useragent#22]
I am getting this when trying to init a new UserAgent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidyu/.virtualenvs/webscraper/lib/python2.7/site-packages/fake_useragent/fake.py", line 10, in **init**
    self.data = load_cached()
  File "/Users/davidyu/.virtualenvs/webscraper/lib/python2.7/site-packages/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/Users/davidyu/.virtualenvs/webscraper/lib/python2.7/site-packages/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/Users/davidyu/.virtualenvs/webscraper/lib/python2.7/site-packages/fake_useragent/utils.py", line 92, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/Users/davidyu/.virtualenvs/webscraper/lib/python2.7/site-packages/fake_useragent/utils.py", line 55, in get_browser_versions
    html = html.split('<div id=\'liste\'>')[1]
IndexError: list index out of range

I believe it is possibly because internetexplorer's BROWSER_BASE_PAGE  is not returning any usable values.

**Comment by hellysmile** [comment]
https://travis-ci.org/hellysmile/fake-useragent/builds/147978486

Latest travis build, which was just rebuilded is green. You are using old version. Try to upgrade!

**Comment by handfulofteeth** [comment]
Ah yes - my fault and my apologies, an upgrade fixed this issue
