### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

### ISSUE THREAD

**Issue by TelBotDev** [fake-useragent/fake-useragent#239]
Suddenly, the code tells me

```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in <module>
    ua = UserAgent()
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/usr/local/lib/python3.7/dist-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

Maybe there are something wrong in ```https://fake-useragent.herokuapp.com/browsers/0.1.11```

**Comment by melroy89** [comment]
You're using a very old version upgrade now.

pip install --upgrade fake-useragent

**Comment by TelBotDev** [comment]
> You're using a very old version upgrade now.
> 
> pip install --upgrade fake-useragent

After it is updated, it tells me,

`WARNING - Error occurred during getting browser: ie, but was suppressed with fallback.`

I think there is still something changed in server side.

**Comment by melroy89** [comment]
No. We don't use server side anymore everything is now client side.

Anyhow. No. The problem is now that you need to use edge. We don't have ie anymore.

**Comment by TelBotDev** [comment]
> edge

Thanks for your info. My code has some problem if I use edge rather than ie now. It tells me

`Please turn JavaScript on and reload the page.`

after I changed from ua.ie to ua.edge.

**Comment by melroy89** [comment]
fake-useragent only generates a user agent string...
