### ISSUE TITLE
having issue when making .exe using pyinstaller

### ISSUE THREAD

**Issue by Abhinavchandra123** [fake-useragent/fake-useragent#257]
Unable to find local data/json file or could not parse the contents using importlib-resources. Try pkg-resource next.
Traceback (most recent call last):
  File "fake_useragent\utils.py", line 21, in load
  File "importlib\resources\_common.py", line 46, in wrapper
  File "importlib\resources\_common.py", line 56, in files
  File "functools.py", line 909, in wrapper
  File "importlib\resources\_common.py", line 82, in _
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fake_useragent.data'

**Comment by melroy89** [comment]
See solutions:

https://github.com/fake-useragent/fake-useragent/issues/155#issuecomment-1336502286


If this works, you could share my your steps and the final solution so I will add it to the readme?

**Comment by melroy89** [comment]
See also: https://github.com/fake-useragent/fake-useragent/issues/278
