### ISSUE TITLE
Still IndexError: list index out of range

### ISSUE THREAD

**Issue by nemesis7331** [fake-useragent/fake-useragent#26]
I've seen u have already fixed this problem but it still appears to me :(

```
root@vmi52271:~/# pip install --upgrade fake-useragent
Collecting fake-useragent
  Downloading fake-useragent-0.1.2.tar.gz
Building wheels for collected packages: fake-useragent
  Running setup.py bdist_wheel for fake-useragent ... done
  Stored in directory: /root/.cache/pip/wheels/be/63/15/f6e26846756da814630681d9fd98d53310426a8464289d7455
Successfully built fake-useragent
Installing collected packages: fake-useragent
Successfully installed fake-useragent-0.1.2
root@vmi52271:~/# pip install -U fake-useragent
Requirement already up-to-date: fake-useragent in /usr/local/lib/pypy2.7/dist-packages
```

```
root@vmi52271:~/# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fake_useragent import UserAgent
>>> ua = UserAgent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 92, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 55, in get_browser_versions
    html = html.split('<div id=\'liste\'>')[1]
IndexError: list index out of range
```

thanks for the great work

**Comment by hellysmile** [comment]
Have You tried to update package? I've just rebuilded package on travis, and build is green.
https://travis-ci.org/hellysmile/fake-useragent/builds/163625039
