### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by KevKeyingLi** [fake-useragent/fake-useragent#32]
When I try use `ua = UserAgent()` on a EC2 ubuntu instance, I get this error: 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/fake.py", line 13, in __init__
        self.load()
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/fake.py", line 17, in load
        self.data = load_cached()
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/utils.py", line 135, in load_cached
        update()
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/utils.py", line 130, in update
        write(load())
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/utils.py", line 96, in load
        browsers_dict[browser_key] = get_browser_versions(browser)
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/utils.py", line 61, in get_browser_versions
        html = get(settings.BROWSER_BASE_PAGE.format(browser=quote_plus(browser)))
      File "/home/ubuntu/cncases/local/lib/python3.4/site-packages/fake_useragent/utils.py", line 27, in get
        return urlopen(request, timeout=settings.HTTP_TIMEOUT).read()
      File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.4/urllib/request.py", line 463, in open
        response = self._open(req, data)
      File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
        '_open', req)
      File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
        r = h.getresponse()
      File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
        response.begin()
      File "/usr/lib/python3.4/http/client.py", line 351, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/usr/lib/python3.4/socket.py", line 374, in readinto
        return self._sock.recv_into(b)
    socket.timeout: timed out

The machine definitely have internet connection since I can ping google. Also, this only happens to a few instances I established this week. The ones from last month are still running properly. I have update fake-useragent to its most recent version 0.1.2.

**Comment by philonor** [comment]
See #4, #30. This is due to useragentstring.com being down.

**Comment by philonor** [comment]
You may use this as a workaround:
```
import fake_useragent
import logging

""" User agent helper class. Allows to get random user agents.
"""
class UserAgent(object):
    ua = None

    """ Returns a random user agent (if database is available),
        otherwise a default one.
        TODO include default user agent table
    """
    @classmethod
    def random(cls):
        if cls.ua is None:
            logger = logging.getLogger(__name__)
            logger.info('Initializing UserAgent using fake_useragent...')
            try:
                cls.ua = fake_useragent.UserAgent()
                # you may replace this by .load()
                cls.ua.load_cached()
            except:
                logger.error('Error initializing UserAgent using fake_useragent.')
                logger.info('Falling back to default User-Agent.')
                cls.ua = False
                return UserAgent.random()
        elif cls.ua is not False:
            return cls.ua.random()
        else:
            # specify a default user agent
            return 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36'
```

And use it:
`UserAgent.random()`

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/pull/33 fixes, new release in 10 min

**Comment by philipperemy** [comment]
`sudo pip install fake-useragent --upgrade` will solve your issue.
