### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by geonyoro** [fake-useragent/fake-useragent#338]
![Screenshot from 2024-07-01 14-18-07](https://github.com/fake-useragent/fake-useragent/assets/10379310/4eccdcbd-2f29-40d9-b66f-30ff6be3cbbe)

Running a process that uses the concurrent.futures.ThreadPoolExecutor with 10 threads. It's iterating over 34k items. Each thread calls After about 1000 items, we hit an io.Error with too many open files.

Log Lines:
--------------
2024-07-01 14:16:29,242 - fake_useragent - WARNING - ThreadPoolExecutor-0_13 - Could not find local data/json file or could not parse the contents using pkg-resource.
Traceback (most recent call last):
  File "/home/george/repos/pj/serverscripts/env/lib/python3.11/site-packages/fake_useragent/utils.py", line 21, in load
    ilr.files("fake_useragent.data").joinpath("browsers.json").read_text()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/resources/readers.py", line 87, in joinpath
    for file in self.iterdir():
  File "/usr/local/lib/python3.11/importlib/resources/_itertools.py", line 31, in unique_everseen
    for element in iterable:
  File "/usr/local/lib/python3.11/importlib/resources/readers.py", line 70, in <genexpr>
    files = (file for path in self._paths for file in path.iterdir())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '/home/george/repos/pj/serverscripts/env/lib/python3.11/site-packages/fake_useragent/data'

**Comment by melroy89** [comment]
fake-useragent is reading the browsers info from disk ([browsers.json](https://github.com/fake-useragent/fake-useragent/blob/main/src/fake_useragent/data/browsers.json)), so there is no external HTTP request or internet connection required to get an UA string.

Instead of creating constantly new `FakeUserAgent` classes, you can reuse the same `FakeUserAgent` instance object and call the methods multiple times like calling `ua.random` multiple times instead.

The "Too many open files" is a Linux file open limit defined in `/etc/security/limits.conf` file on your distro for your user (george). `nofile` can have a soft and hard limit. You could also increase the `nofile` limit for that user.. 

However, again I do recommend instead of rewrite you code in order to reuse the FakeUserAgent object as often as you can. Meaning with 10 threads, I expect no more than 10 open files.
