### ISSUE TITLE
urllib2.URLError: <urlopen error timed out>

### ISSUE THREAD

**Issue by anshuman91** [fake-useragent/fake-useragent#34]
>>> from fake_useragent import UserAgent
>>> ua = UserAgent()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 17, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 21, in load
    self.data = load_cached()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 138, in load_cached
    update()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 133, in update
    write(load())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 99, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 64, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE.format(browser=quote_plus(browser)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 29, in get
    return urlopen(request, timeout=settings.HTTP_TIMEOUT).read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error timed out>

**Comment by anshuman91** [comment]
I am having this issue from last 2 days. I just upgraded the fake-useragent library but still having the issue.

**Comment by pcinkh** [comment]
@anshuman91 it will be fixed in nearest 24 hours, I'm working on https://github.com/hellysmile/fake-useragent/pull/33

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/pull/33

fixes, new release in 10 min

**Comment by anshuman91** [comment]
Yeah it's working now. Thank you all. 👍
