### ISSUE TITLE
fake_useragent 2.0 fails for Python 3.8

### ISSUE THREAD

**Issue by xqt** [fake-useragent/fake-useragent#406]
**fake_useragent** 2.0 fails for **Python 3.8**. Here is a traceback for it:
```
======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pywikibot/pywikibot/tests/__init__.py", line 262, in load_tests
    return collector(loader)
  File "/home/runner/work/pywikibot/pywikibot/tests/__init__.py", line 253, in collector
    tests = loader.loadTestsFromNames(test_list)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/pywikibot/pywikibot/tests/http_tests.py", line 245, in <module>
    class LiveFakeUserAgentTestCase(HttpbinTestCase):
  File "/home/runner/work/pywikibot/pywikibot/tests/aspects.py", line 275, in test_requirement
    __import__(required_module, globals(), locals(), [], 0)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fake_useragent/__init__.py", line 4, in <module>
    from fake_useragent.fake import FakeUserAgent, UserAgent
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fake_useragent/fake.py", line 8, in <module>
    from fake_useragent.utils import BrowserUserAgentData, load
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fake_useragent/utils.py", line 42, in <module>
    def load() -> list[BrowserUserAgentData]:
TypeError: 'type' object is not subscriptable

----------------------------------------------------------------------
```
See https://github.com/wikimedia/pywikibot/actions/runs/12203270152/job/34050802363 for other examples

Possible solutions
--
- restrict fake_useragent to Python 3.9+
-  add `from __future__ import annotations` to your scripts to enable string annotations
-  use typing.List instead of list for annotations, deprecated since Python 3.9, see https://docs.python.org/3/library/typing.html#typing.List

**Comment by melroy89** [comment]
Python 3.8 is end of life.

**Comment by xqt** [comment]
> Python 3.8 is end of life.

Sure but it would be highly appropriate to add

`requires-python = ">=3.9.0"`

within your pyproject.toml. This would prevent including newer fake_useragent releases with older Pythons.
See https://packaging.python.org/en/latest/guides/dropping-older-python-versions/

**Comment by melroy89** [comment]
Agreed!

**Comment by melroy89** [comment]
Seems like an issue in PR: https://github.com/fake-useragent/fake-useragent/pull/352 by @sebastian-correa. Why do we still have python_version?

**Comment by melroy89** [comment]
There seems also be a https://peps.python.org/pep-0621/#requires-python like @xqt is mentioning. I will add this.

**Comment by melroy89** [comment]
Added: https://github.com/fake-useragent/fake-useragent/commit/87426ff0ea47143d4d2135c828cb00807aae4a27

I will create a new release v2.0.1

**Comment by melroy89** [comment]
tag 2.0.1 is also released now.
