### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

### ISSUE THREAD

**Issue by zhangslob** [fake-useragent/fake-useragent#56]

**Comment by zhangslob** [comment]
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.7
Traceback (most recent call last):
  File "d:\Users\zaoshu\Anaconda3\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 1392, in connect
    super().connect()
  File "d:\Users\zaoshu\Anaconda3\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\Users\zaoshu\Anaconda3\lib\socket.py", line 722, in create_connection
    raise err
  File "d:\Users\zaoshu\Anaconda3\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out


Why？

**Comment by hellysmile** [comment]
Can You try to open https://fake-useragent.herokuapp.com/browsers/0.1.7 in Your browser?

**Comment by hellysmile** [comment]
I do no enough data to debug, open new issue if it is still fails

**Comment by Laotanling** [comment]
HI ,I can open the link but  I don't know how to fix it , I try cache=False,use_cache_server=False,verify_ssl=False, but still get the same problem?

**Comment by zhangslob** [comment]
@Laotanling Because you in China

**Comment by gdoudeng** [comment]
> @Laotanling Because you in China

。。。好家伙
