### ISSUE TITLE
fake-useragent.herokuapp.com unreliable uptime

### ISSUE THREAD

**Issue by chocolatkey** [fake-useragent/fake-useragent#62]
It seems the cache server is unreliably available, as my programs are failing. They are trying to load "https://fake-useragent.herokuapp.com/browsers/0.1.8". Sometimes when I visit this page in a browser it is available (loading "browsers": {"chrome":.....), most of the time I am getting a connection closed error:
![image](https://user-images.githubusercontent.com/13407784/32928840-f2226762-cb08-11e7-9e93-5a0a6a337a98.png)
```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\fake_useragent\utils.py", line 67, in get
    context=context,
  File "C:\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by hellysmile** [comment]
Hmm, sounds like a high-load problem ;) I am considering to move backup files just to s3 + cloudfront, I'll do minor quick-fix release on next Monday(November 20)

**Comment by chocolatkey** [comment]
Thanks

**Comment by hellysmile** [comment]
Release 0.1.9 moved to s3 + cloudfront http://d2g6u4gh6d9rq0.cloudfront.net/browsers/fake_useragent_0.1.9.json
