### ISSUE TITLE
Cant run it on QPython on Android 

### ISSUE THREAD

**Issue by Sudge3** [fake-useragent/fake-useragent#65]
I get this out of the errors.log 

> WARNING:root:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
FakeUserAgentError: Maximum amount of retries reached
WARNING:root:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
FakeUserAgentError: Maximum amount of retries reached

And this out of executing the script
> /data/user/0/org.qpython.qpy/files/bin/qpython-android5-root.sh
 "/storage/emulated/0/qpython/instabot.py-master/main.py" && exit
/instabot.py-master/main.py" && exit    <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/instabot.py-master/main.py", line 77, in <module>
    'yuki_nishitani8','contemporary.paintings','danteslens','ramontrotman','voidcrack',])
  File "/storage/emulated/0/qpython/instabot.py-master/src/instabot.py", line 162, in __init__    fake_ua = UserAgent()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/fake.py", line 69, in __init__    self.load()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 245, in update    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
1|bullhead:/ $

Can someone tell me what is wrong? Have no issus on Windows or Mac

**Comment by hellysmile** [comment]
Can You try?

```python
import requests
requests.get('https://fake-useragent.herokuapp.com/browsers/0.1.8')
```

**Comment by Sudge3** [comment]
in which .py document should i paste this? :D

**Comment by Sudge3** [comment]
@hellysmile i get "<response[200]>"

**Comment by Sudge3** [comment]
@hellysmile Can you help me please

**Comment by hellysmile** [comment]
Ill test on qpython today

**Comment by hellysmile** [comment]
![screenshot_20180131-193239](https://user-images.githubusercontent.com/1834317/35637799-fc128a54-06bd-11e8-8d93-b68bb5a881bf.png)

**Comment by hellysmile** [comment]
Closing, as can not reproduce, works fine for me
