### ISSUE TITLE
user agent throws "ValueError: could not convert string to float" error - on both cached /uncached calls

### ISSUE THREAD

**Issue by ekta1007** [fake-useragent/fake-useragent#7]
from fake_useragent import UserAgent
on calling ua = UserAgent() or ua = UserAgent(cache=False)

Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    ua = UserAgent()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent-0.0.6-py2.7.egg/fake_useragent/fake.py", line 12, in **init**
    self.data = load_cached()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent-0.0.6-py2.7.egg/fake_useragent/utils.py", line 134, in load_cached
    update()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent-0.0.6-py2.7.egg/fake_useragent/utils.py", line 129, in update
    write(load())
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent-0.0.6-py2.7.egg/fake_useragent/utils.py", line 88, in load
    for counter in range(int(float(percent))):
ValueError: could not convert string to float: <a

**Comment by hellysmile** [comment]
Hey, new version was pushed to pypi a couple of days ago, have You tried latest build?

**Comment by ekta1007** [comment]
Just upgraded . Works now. Thanks.

**Comment by ImanYZ** [comment]
I upgraded to the last version, but returns the same error message!

**Comment by hellysmile** [comment]
@ImanYZ, just checked and seems to be working fine. Can You give me full traceback?

**Comment by ImanYZ** [comment]
Hi @hellysmile,
Thank you for your concern.
I thought this thread was closed. That's why I asked my complete question in a new thread called:
ValueError: could not convert string to float: <a
Best regards,
ImanYZ

**Comment by hellysmile** [comment]
@ImanYZ , ok, https://github.com/hellysmile/fake-useragent/issues/9
