### ISSUE TITLE
try/except block doesn't catch caching server access errors

### ISSUE THREAD

**Issue by essandess** [fake-useragent/fake-useragent#78]
I'm trying to catch errors that occur when the caching server doesn't respond (see #77).

But the existing exception handling prevents catching these (common) errors in a `try`/`except` block.

This is a request to modify exception handling so that on such an exception program control passes to the script calling `fake_useragent`.

```python
import fake_useragent as fake_ua
fua = fake_ua.UserAgent()
try:
    fua.update()
except Exception as e:
   print(f'User agent exception: {e}')
```

Error (uncaught):
```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by rix1337** [comment]
+1

**Comment by kngxscn** [comment]
+1

**Comment by sloth2012** [comment]
+1

**Comment by rix1337** [comment]
Has anyone been able to solve this?

**Comment by rix1337** [comment]
Is there a maintained fork of this project?

**Comment by CosmicHorrorDev** [comment]
If you're having the same issue as me, then it looks like line 166 in `utils.py` is the one raising the error and it ends up falling back to using the cache server. I'm assuming it's the `logger.warning` on line 180 that is causing the error to get printed to the terminal, but it then loads from the caching server.

So in my case, it will print out the error to terminal (which is annoying), but still succeed in falling back to using the caching server, so the reason the error isn't being caught by your `try` `except` is because it is caught internally. Hope this helps!

**Comment by coffeeincodeout** [comment]
getting the same issue. @LovecraftianHorror what folder would this be in?

**Comment by CosmicHorrorDev** [comment]
It's in the library itself so the backtrace should say where the location of the file is for your specific install, but for the library it is `fake_useragent/utils.py`

**Comment by coffeeincodeout** [comment]
i see what you're saying and thank you. So its falling back which is good we just need to find a way to fix this so it doesn't display.

**Comment by CosmicHorrorDev** [comment]
Correct, the two easy ways I could think of are changing the `.warning` to `.info` or changing the root logger to default to something higher than `WARN` with
```python
logging.getLogger().setLevel(logging.ERROR)
```
in `fake_useragent/log.py` so that errors and above are shown in terminal. But I'm not too familiar with with this library so I would like suggestions/corrections.

**Comment by gmagno** [comment]
Yup, no exception is raised. It is just printing a traceback from an already handled exception. A little bit disapointing.

```Python
In [37]: from fake_useragent import UserAgent
    ...: try:
    ...:     ua = UserAgent(cache=False)
    ...:     print("====================> no exception was raised")
    ...: except (FakeUserAgentError) as e:
    ...:     print("---------------------> an exception was raised")
    ...:
```
```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "~/.pyenv/versions/3.8.3/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "~/.pyenv/versions/3.8.3/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "~/.pyenv/versions/3.8.3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "~/.pyenv/versions/3.8.3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.3/envs/nfe-parser_3.8.3/lib/python3.8/site-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.3/envs/nfe-parser_3.8.3/lib/python3.8/site-packages/fake_useragent/utils.py", line 164, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "~/.pyenv/versions/3.8.3/envs/nfe-parser_3.8.3/lib/python3.8/site-packages/fake_useragent/utils.py", line 120, in get_browser_versions
    html = get(
  File "~/.pyenv/versions/3.8.3/envs/nfe-parser_3.8.3/lib/python3.8/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```
```Python
====================> no exception was raised
```

**Comment by gmagno** [comment]
One possible solution: don't let the function call to polute `stderr`. Temporarily redirect it to `/dev/null`:

Note: the argument `cache` is set to `False` to trigger the traceback, in general you should leave it as `True`.

```python
import os
import sys
import fake_useragent

# redirect stderr to /dev/null so that `fake_useragent.UserAgent()`
# method does not polute stdout (this is an unfortunate bug, already
# reported in https://github.com/hellysmile/fake-useragent/issues/78)
sys.stderr = open(os.devnull, "w")
try:
    ua = fake_useragent.UserAgent(cache=False)
except fake_useragent.errors.FakeUserAgentError:
    # something went wrong with fake_useragent... just hardcode a user agent
    ua_text = (
        "Mozilla/5.0 (X11; CrOS i686 2268.111.0) AppleWebKit/536.11 "
        "(KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11"
    )
else:
    ua_text = ua.random
finally:
    sys.stderr = sys.__stderr__

print(ua_text)
```

**Comment by melroy89** [comment]
Solved by now. Upgrade to the latest release:

```sh
pip install --upgrade fake-useragent
```
