### ISSUE TITLE
[CRITICAL] http://www.useragentstring.com/ down

### ISSUE THREAD

**Issue by 0xfede7c8** [fake-useragent/fake-useragent#99]
This site being down renders the package useless.

**Comment by tonal** [comment]
see #95

**Comment by 0xfede7c8** [comment]
I was aware of that issue, thanks. I would normally not replicate issues unless I wanted to bring attention to the discussion. I wanted to do it because of the importance of the problem.

**Comment by g0per** [comment]
If the cache server happened to be up, it could fix this downtime (I guess it'd be DDoSed to death by the users tho). But it's also offline.

**Comment by sreecodeslayer** [comment]
@g0per yes, you are right about the heroku cache server being down, but it is weird:

> If the cache server happened to be up, it could fix this downtime (I guess it'd be DDoSed to death by the users tho). But it's also offline.

```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 164, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 120, in get_browser_versions
    html = get(
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```
Opening https://fake-useragent.herokuapp.com/browsers/0.1.11 in the browser gives a valid response, but the retries within the package is failing. 🤔 

Just curious: Could this be a case of heroku cache server being down due to inactivity? But then the retry requests should wake it up right?

**Comment by melroy89** [comment]
It's solved now. Package the package: `pip install --upgrade fake-useragent`
